language: python
python:
- 2.7
- 3.8
- 3.7
- 3.6
- 3.5
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: ahmed_bodi
  on:
    tags: true
    repo: ahmedbodi/Rage4
    python: 2.7
  password:
    secure: f0K2TaeUucOUSEtZijNkcwvpo60mjAilSyzrCrPw6w1cNGXtoKp1VWrFY18TXWw7ceTD9kMqWoTDK9HllaD3HC36FFU6PbCFHsBDLAIbHFWoE3+J4Z8pzWhGcoZC1KwmDAy7ZxADLDURJRBWNF5opPUQ0u2aujKMfEXf1kFTK0TyA/MF6CmebC+47H5/EfMKJTDFgjmgliVnYHTWFz9ebo80PhamJx1vn2HeKC3IinyuZC1j72elqJfT87oBEjXF99lIA22ekL9KqTW+nq4MgLosyErJs6Q4vaphHdMSsu/HYGEjuA/LjNp+6l5qTq29Iqbu1cAvsfmIFYXCcjInkclAaGZ6xLfNC52NMbVW+ePhMTyaRavxG8Y1t6Mm3bqHsUjlKJ1C7R+A9x1AxSuWfzSebWG+jQ+N+hVzsdt0Z2A58a6/11yl+Oe21OlO0ZrwOLPtb/nAyDHQv0i8T6N1BPH4IGtmQajMtJzjFQaFF1KCeoGqlKzwkUGeMIEax1xLXp3XkTGeGfDiEsY0OD8UoY3mdjCpEASEaWr3sdfyfyOCBgvaO1Qm2w/7+FB6sd5fcrqenBVVHS/hbSBUBy96RVO7x8CjBvPRKnbNDu9yp7fZd3or+XHPSAvKAOLSmW1EA3lfG2xK2qwGlhmfV7aec7gV6VKRR9RggtibnKZ8FD8=
